 name: Azure Web App Deployment

on:
  push:
    branches:
      - main  # Main branch me push hone par trigger hoga

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'  # Apne project ke Python version ke hisaab se change karein

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: transaztestap       # Replace with your Azure Web App name
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
        package: .
